"""Update relationship on Institution and Account tables

Revision ID: 3ee28f6672f1
Revises: 55a539ecc5dd
Create Date: 2020-03-21 19:12:34.893419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ee28f6672f1'
down_revision = '55a539ecc5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('institution_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'account', 'institution', ['institution_id'], ['id'])
    op.drop_constraint('institution_ibfk_1', 'institution', type_='foreignkey')
    op.drop_column('institution', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('institution_ibfk_1', 'institution', 'account', ['account_id'], ['id'])
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'institution_id')
    # ### end Alembic commands ###
