"""Add type and subtype to account

Revision ID: 572dc18a2595
Revises: 3ee28f6672f1
Create Date: 2020-03-21 19:23:21.989924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572dc18a2595'
down_revision = '3ee28f6672f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('subtype', sa.String(length=50), nullable=True))
    op.add_column('account', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'type')
    op.drop_column('account', 'subtype')
    # ### end Alembic commands ###
