"""Added partner id to user

Revision ID: 6beec7e1cdbc
Revises: aaf25bc3c388
Create Date: 2021-10-20 21:18:43.706222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6beec7e1cdbc'
down_revision = 'aaf25bc3c388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transaction', ['transaction_id'])
    op.add_column('user', sa.Column('partner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'partner_id')
    op.drop_constraint(None, 'transaction', type_='unique')
    # ### end Alembic commands ###
