"""empty message

Revision ID: ab4a8c007e9d
Revises: 572dc18a2595
Create Date: 2021-01-14 21:41:38.917171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4a8c007e9d'
down_revision = '572dc18a2595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('account', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_constraint('account_ibfk_2', 'account', type_='foreignkey')
    op.drop_constraint('account_ibfk_1', 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'institution', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'])
    op.add_column('balance', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('balance', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_constraint('balance_ibfk_1', 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key('balance_ibfk_1', 'balance', 'account', ['account_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('balance', 'updated_on')
    op.drop_column('balance', 'created_on')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key('account_ibfk_1', 'account', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('account_ibfk_2', 'account', 'institution', ['institution_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('account', 'updated_on')
    op.drop_column('account', 'created_on')
    op.drop_table('bank_access')
    # ### end Alembic commands ###
